version: '3.9'

services:
    php:
        build:
            context: ./docker/php
            args:
                phpunit_version: 9.5.4
        working_dir: /app
        volumes:
            - '.:/app'
        user: '${UID:-1000}:${GID:-1000}'
    database:
        image: postgres:15.3-alpine
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: test_backend
        ports:
            - "5434:5432"
        volumes:
            - database_data:/var/lib/postgresql/data:rw
            - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    database_data: